#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then you need to set the SHELL environment variable to point to
#       that shell before running this script, like "export SHELL=/bin/bash".
#       If you don't, Gradle might output "gradle: command not found" and exit.
#
#   (2) The script only runs when the `gradle` command is not found. That's why
#       you see `gradle` being invoked in the line that does the actual check.
#       The assumption is that a Gradle daemon is already running, in which case
#       using `gradle` will use the daemon's compatible environment and the init
#       scripts are only run once. But if there is no daemon (e.g., you're
#       running `gradle` for the first time), a compatible but minimal environment
#       will be constructed as well.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$( ls -ld "$app_path" )
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -n is undefined. But we know bash and zsh support it.
        # In POSIX sh, 'ulimit -n' prints the default for shl (e.g. 256), but it's
        # not possible to set it high, because the syntax 'ulimit -n 4096' is not
        # valid in POSIX sh. There is no alias to 'ulimit' to make it work.
        # shellcheck disable=SC3045
        ulimit -n 65536 || warn "Could not raise file descriptor limit" ;;
      * )
        ulimit -n $MAX_FD || warn "Could not raise file descriptor limit to $MAX_FD"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - posix systems use $@ while win32 uses "%*"
    # This is a mess. We'll simply set CYGWIN and MSYS to use non-POSIX mode.
    # The removal of POSIX mode will, among other things, cause directory
    # names like `C:\Program Files` to be treated as a single long argument
    # which will become `C:\Program` and `Files` as separate arguments with
    # the former one not a directory, so the script breaks. Removing POSIX
    # mode is not a perfect solution, but it's a lot better than auto-magically
    # converting all drives to UNC points. The `//` prefix seems to work for
    # directories.
    unset POSIXLY_CORRECT
    export CYGWIN=win32
    export MSYS=win32
fi

# Collect all arguments for the java command;
#   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_OPTS can contain fragments of
#     shell script including quotes and variable substitutions, so put them in
#     double quotes to make sure that they get re-expanded; and
#   * put everything else in single quotes, so that it is not re-expanded.

set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Stop when "xargs" is not available.
if ! command -v xargs >/dev/null 2>&1
then
    die "xargs is not available"
fi

# Use "xargs" to parse quoted args.
#
# With -n1 it outputs one arg per line, with the quotes and backslashes removed.
#
# In Bash we could simply go:
#   readarray ARGS < <( xargs -n1 <<<"$var" ) &&
#   set -- "${ARGS[@]}"
#
# In POSIX sh we don't know arrays, so we have a convoluted run of while loops.
# The non-POSIX way (bash/ksh/zsh) is much simpler, but we don't want to require
# a modern shell for this legacy script. So we'll keep the old way.

# Using split + eval to avoid having to expand in a subhell because we can't pass
# an array through an environment variable (and we can't easily unset/rewrite a
# direct assignment). We use \LINE as the IFS temporarily.
IFS=\ LINE
set -- $( xargs -n1 <<<"$*" )
IFS=' '

# Ultimately, apply the arguments. We cannot use "$@" because
# that would apply all arguments in one argument if IFS is set to the space
# character (the default purpose of this script). And in posh, separating
# arguments with newline leads to each newline being interpreted as a space
# when IFS is set to space by default (which is the posh default). So we must
# "re-quote" the arguments to ensure each arg is passed as one consistent
# argument (delete the leading " we added). The `echo` command prints the
# ARGV array to stdout, and we use `sed` to remove the first ' ' character.
LINE=$( printf '%s\n' "$*" | sed -e 's/^ //' )
eval set -- "$LINE"

# Check for an archive wrapper. Gradle (gradlew) expects that the `$APP_HOME` path
# is the directory of the wrapper script, and that the wrapper jar is in the wrapper
# directory relative to that path. Check for the file to avoid the script failing
# when the wrapper directory doesn't exist.
if [ -e "$APP_HOME/gradle/wrapper/gradle-wrapper.jar" ]; then
    exec "$JAVACMD" "$@"
else
    die "Could not find gradle-wrapper.jar. This file is required to run gradlew. Please download it from the main Gradle distribution at https://gradle.org/releases."
fi
